// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXCd4nroCcqDM71OhTTPb1ULyBVaOAxqc',
    appId: '1:458092658772:web:12d62d62b286a9f7f1edc1',
    messagingSenderId: '458092658772',
    projectId: 'meal-f2a2d',
    authDomain: 'meal-f2a2d.firebaseapp.com',
    storageBucket: 'meal-f2a2d.firebasestorage.app',
    measurementId: 'G-Y4N5691S92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYX7FxWSDdPI7gouqNqRjMRw7eBNxZkKA',
    appId: '1:458092658772:android:616579bbe6671d3ff1edc1',
    messagingSenderId: '458092658772',
    projectId: 'meal-f2a2d',
    storageBucket: 'meal-f2a2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5XZQH10eK2cuOc3IV4ltxq0ycn4NTn5U',
    appId: '1:458092658772:ios:bdfdfa43fc9935def1edc1',
    messagingSenderId: '458092658772',
    projectId: 'meal-f2a2d',
    storageBucket: 'meal-f2a2d.firebasestorage.app',
    iosBundleId: 'com.example.mealRecommender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5XZQH10eK2cuOc3IV4ltxq0ycn4NTn5U',
    appId: '1:458092658772:ios:bdfdfa43fc9935def1edc1',
    messagingSenderId: '458092658772',
    projectId: 'meal-f2a2d',
    storageBucket: 'meal-f2a2d.firebasestorage.app',
    iosBundleId: 'com.example.mealRecommender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXCd4nroCcqDM71OhTTPb1ULyBVaOAxqc',
    appId: '1:458092658772:web:b3aaf88bef27c2fbf1edc1',
    messagingSenderId: '458092658772',
    projectId: 'meal-f2a2d',
    authDomain: 'meal-f2a2d.firebaseapp.com',
    storageBucket: 'meal-f2a2d.firebasestorage.app',
    measurementId: 'G-MRELELSS6F',
  );
}
